import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type {
  ApiSpec,
  EnumType,
  ObjectType,
  Operation,
  Property,
  ServiceGroup,
  TypeRef,
} from "../ir.js";

function typeRefToPython(ref: TypeRef): string {
  switch (ref.kind) {
    case "primitive":
      switch (ref.type) {
        case "string": return "str";
        case "number": return "float";
        case "integer": return "int";
        case "boolean": return "bool";
      }
      break;
    case "ref":
      return ref.name;
    case "array":
      return `list[${typeRefToPython(ref.items)}]`;
    case "enum": {
      const values = ref.values.map((v) => (typeof v === "string" ? `"${v}"` : v)).join(", ");
      return `Literal[${values}]`;
    }
    case "union":
      return ref.variants.map(typeRefToPython).join(" | ");
    case "object":
      if (ref.name) return ref.name;
      return "dict[str, Any]";
    case "map":
      return `dict[str, ${typeRefToPython(ref.valueType)}]`;
  }
  return "Any";
}

function toSnakeCase(s: string): string {
  return s
    .replace(/([a-z])([A-Z])/g, "$1_$2")
    .replace(/[-.\s]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "")
    .toLowerCase();
}

function toPascalCase(slug: string): string {
  return slug
    .split("-")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

function generatePydanticModel(model: ObjectType): string {
  const lines: string[] = [];
  if (model.description) {
    lines.push(`    """${model.description}"""`);
  }
  if (model.properties.length === 0) {
    lines.push(`    pass`);
    return [`class ${model.name}(BaseModel):`, ...lines].join("\n");
  }

  for (const prop of model.properties) {
    const pyName = toSnakeCase(prop.name);
    let pyType = typeRefToPython(prop.type);
    if (prop.nullable) pyType = `${pyType} | None`;
    const alias = pyName !== prop.name ? ` = Field(alias="${prop.name}")` : "";
    const defaultVal =
      !prop.required && !alias ? " = None" : !prop.required ? "" : "";

    if (!prop.required && pyType.indexOf("None") === -1) {
      pyType = `${pyType} | None`;
    }

    const suffix = !prop.required && !alias ? " = None" : alias;
    lines.push(`    ${pyName}: ${pyType}${suffix}`);
  }

  return [`class ${model.name}(BaseModel):`, ...lines].join("\n");
}

function generateEnumLiteral(model: EnumType): string {
  const values = model.values
    .map((v) => (typeof v === "string" ? `"${v}"` : v))
    .join(", ");
  return `${model.name} = Literal[${values}]`;
}

function generateModels(spec: ApiSpec): string {
  const lines: string[] = [
    "# Generated by Ingot — do not edit manually.",
    "",
    "from __future__ import annotations",
    "",
    "from typing import Any, Literal",
    "",
    "from pydantic import BaseModel, Field",
    "",
    "",
  ];

  for (const [, model] of spec.models) {
    if (model.kind === "object") {
      lines.push(generatePydanticModel(model as ObjectType));
    } else if (model.kind === "enum") {
      lines.push(generateEnumLiteral(model as EnumType));
    } else {
      lines.push(`${model.name} = ${typeRefToPython(model)}`);
    }
    lines.push("");
    lines.push("");
  }

  return lines.join("\n");
}

function buildMethodSignature(op: Operation): string {
  const params: string[] = ["self"];

  for (const param of op.parameters.filter((p) => p.location === "path")) {
    params.push(`${toSnakeCase(param.name)}: ${typeRefToPython(param.type)}`);
  }

  for (const param of op.parameters.filter((p) => p.location === "query")) {
    const pyType = typeRefToPython(param.type);
    if (param.required) {
      params.push(`${toSnakeCase(param.name)}: ${pyType}`);
    } else {
      params.push(`${toSnakeCase(param.name)}: ${pyType} | None = None`);
    }
  }

  if (op.requestBody) {
    const bodyType = typeRefToPython(op.requestBody.type);
    if (op.requestBody.required) {
      params.push(`body: ${bodyType}`);
    } else {
      params.push(`body: ${bodyType} | None = None`);
    }
  }

  return params.join(", ");
}

function buildReturnType(op: Operation): string {
  const success = op.responses.find(
    (r) => r.statusCode >= 200 && r.statusCode < 300 && r.type,
  );
  if (!success?.type) return "None";
  return typeRefToPython(success.type);
}

function buildUrlExpression(op: Operation): string {
  if (!op.parameters.some((p) => p.location === "path")) {
    return `"${op.path}"`;
  }
  return `f"${op.path.replace(/\{(\w+)\}/g, (_, name) => `{${toSnakeCase(name)}}`)}"`;
}

function generateResourceClass(group: ServiceGroup): string {
  const className = toPascalCase(group.name) + "Resource";
  const lines: string[] = [
    `class ${className}:`,
    `    def __init__(self, client: "IngotClient") -> None:`,
    `        self._client = client`,
    "",
  ];

  for (const op of group.operations) {
    const methodName = toSnakeCase(op.id);
    const sig = buildMethodSignature(op);
    const returnType = buildReturnType(op);
    const url = buildUrlExpression(op);

    lines.push(`    def ${methodName}(${sig}) -> ${returnType}:`);
    if (op.description) {
      lines.push(`        """${op.description}"""`);
    }

    const queryParams = op.parameters.filter((p) => p.location === "query");
    if (queryParams.length > 0) {
      lines.push(`        params = {`);
      for (const q of queryParams) {
        lines.push(`            "${q.wireName}": ${toSnakeCase(q.name)},`);
      }
      lines.push(`        }`);
    }

    lines.push(`        return self._client.request(`);
    lines.push(`            method="${op.method.toUpperCase()}",`);
    lines.push(`            path=${url},`);
    if (queryParams.length > 0) {
      lines.push(`            params={k: v for k, v in params.items() if v is not None},`);
    }
    if (op.requestBody) {
      lines.push(`            json=body.model_dump(by_alias=True, exclude_none=True) if body else None,`);
    }
    lines.push(`        )`);
    lines.push("");
  }

  return lines.join("\n");
}

function generateClientModule(spec: ApiSpec): string {
  const lines: string[] = [
    "# Generated by Ingot — do not edit manually.",
    "",
    "from __future__ import annotations",
    "",
    "import time",
    "from typing import Any",
    "",
    "import httpx",
    "",
  ];

  for (const group of spec.groups) {
    const className = toPascalCase(group.name) + "Resource";
    lines.push(`from .resources.${toSnakeCase(group.name)} import ${className}`);
  }

  lines.push("");
  lines.push("");
  lines.push("class IngotClient:");
  lines.push(`    def __init__(`);
  lines.push(`        self,`);
  lines.push(`        *,`);
  lines.push(`        base_url: str = "${spec.baseUrl}",`);

  for (const auth of spec.auth) {
    if (auth.strategy === "bearer" || auth.strategy === "apiKey") {
      lines.push(`        api_key: str | None = None,`);
    } else if (auth.strategy === "basic") {
      lines.push(`        username: str | None = None,`);
      lines.push(`        password: str | None = None,`);
    }
  }

  lines.push(`        timeout: float = 30.0,`);
  lines.push(`        max_retries: int = 2,`);
  lines.push(`    ) -> None:`);
  lines.push(`        self._base_url = base_url.rstrip("/")`);
  lines.push(`        self._timeout = timeout`);
  lines.push(`        self._max_retries = max_retries`);
  lines.push(`        headers: dict[str, str] = {"Content-Type": "application/json"}`);

  for (const auth of spec.auth) {
    if (auth.strategy === "bearer") {
      lines.push(`        if api_key:`);
      lines.push(`            headers["Authorization"] = f"Bearer {api_key}"`);
    } else if (auth.strategy === "apiKey") {
      const header = auth.headerName ?? "X-API-Key";
      lines.push(`        if api_key:`);
      lines.push(`            headers["${header}"] = api_key`);
    }
  }

  lines.push(`        self._client = httpx.Client(base_url=self._base_url, headers=headers, timeout=timeout)`);
  lines.push("");

  for (const group of spec.groups) {
    const className = toPascalCase(group.name) + "Resource";
    lines.push(`        self.${toSnakeCase(group.name)} = ${className}(self)`);
  }

  lines.push("");
  lines.push(`    def request(self, *, method: str, path: str, params: dict[str, Any] | None = None, json: Any = None) -> Any:`);
  lines.push(`        last_error: Exception | None = None`);
  lines.push(`        for attempt in range(self._max_retries + 1):`);
  lines.push(`            if attempt > 0:`);
  lines.push(`                time.sleep(min(2 ** attempt, 8))`);
  lines.push(`            try:`);
  lines.push(`                response = self._client.request(method, path, params=params, json=json)`);
  lines.push(`                if response.status_code >= 500 or response.status_code == 429:`);
  lines.push(`                    last_error = Exception(f"{method} {path} failed: {response.status_code} {response.text}")`);
  lines.push(`                    continue`);
  lines.push(`                response.raise_for_status()`);
  lines.push(`                if response.status_code == 204:`);
  lines.push(`                    return None`);
  lines.push(`                return response.json()`);
  lines.push(`            except httpx.TimeoutException:`);
  lines.push(`                last_error = Exception(f"Request timed out: {method} {path}")`);
  lines.push(`                continue`);
  lines.push(`        raise last_error or Exception("Request failed after retries")`);
  lines.push("");
  lines.push(`    def close(self) -> None:`);
  lines.push(`        self._client.close()`);
  lines.push("");
  lines.push(`    def __enter__(self) -> "IngotClient":`);
  lines.push(`        return self`);
  lines.push("");
  lines.push(`    def __exit__(self, *args: Any) -> None:`);
  lines.push(`        self.close()`);

  return lines.join("\n") + "\n";
}

function generatePyprojectToml(spec: ApiSpec): string {
  const name = spec.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return `[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "${name}"
version = "${spec.version}"
description = "${spec.description ?? `Python SDK for ${spec.name}`}"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.27",
    "pydantic>=2.0",
]
`;
}

function generateInitPy(spec: ApiSpec): string {
  const lines: string[] = [
    "# Generated by Ingot — do not edit manually.",
    "",
    "from .client import IngotClient",
    "",
  ];

  const modelNames: string[] = [];
  for (const [name, model] of spec.models) {
    if (model.kind === "object") {
      modelNames.push(name);
    }
  }
  if (modelNames.length > 0) {
    lines.push(`from .models import ${modelNames.join(", ")}`);
  }

  lines.push("");
  lines.push(`__all__ = ["IngotClient"${modelNames.map((n) => `, "${n}"`).join("")}]`);
  lines.push("");

  return lines.join("\n");
}

async function generatePythonSdk(
  spec: ApiSpec,
  outputDir: string,
): Promise<void> {
  const pkgName = spec.name.toLowerCase().replace(/[^a-z0-9]+/g, "_");
  const pkgDir = join(outputDir, "src", pkgName);
  const resourcesDir = join(pkgDir, "resources");
  await mkdir(resourcesDir, { recursive: true });

  await writeFile(join(outputDir, "pyproject.toml"), generatePyprojectToml(spec));
  await writeFile(join(pkgDir, "__init__.py"), generateInitPy(spec));
  await writeFile(join(pkgDir, "models.py"), generateModels(spec));
  await writeFile(join(pkgDir, "client.py"), generateClientModule(spec));

  // Resources __init__
  const resourceImports: string[] = ["# Generated by Ingot — do not edit manually.", ""];
  for (const group of spec.groups) {
    const className = toPascalCase(group.name) + "Resource";
    resourceImports.push(`from .${toSnakeCase(group.name)} import ${className}`);
  }
  resourceImports.push("");
  await writeFile(join(resourcesDir, "__init__.py"), resourceImports.join("\n"));

  for (const group of spec.groups) {
    const imports: Set<string> = new Set();
    collectModelRefs(group, spec, imports);

    const parts: string[] = [
      "# Generated by Ingot — do not edit manually.",
      "",
      "from __future__ import annotations",
      "",
      "from typing import Any, TYPE_CHECKING",
      "",
      "if TYPE_CHECKING:",
      '    from ..client import IngotClient',
      "",
    ];

    if (imports.size > 0) {
      parts.push(`from ..models import ${[...imports].join(", ")}`);
      parts.push("");
    }

    parts.push("");
    parts.push(generateResourceClass(group));

    await writeFile(
      join(resourcesDir, `${toSnakeCase(group.name)}.py`),
      parts.join("\n"),
    );
  }
}

function collectModelRefs(
  group: ServiceGroup,
  spec: ApiSpec,
  refs: Set<string>,
): void {
  function walk(t: TypeRef): void {
    switch (t.kind) {
      case "ref":
        if (spec.models.has(t.name)) refs.add(t.name);
        break;
      case "array":
        walk(t.items);
        break;
      case "union":
        t.variants.forEach(walk);
        break;
      case "object":
        t.properties.forEach((p) => walk(p.type));
        break;
      case "map":
        walk(t.valueType);
        break;
    }
  }

  for (const op of group.operations) {
    op.parameters.forEach((p) => walk(p.type));
    if (op.requestBody) walk(op.requestBody.type);
    op.responses.forEach((r) => {
      if (r.type) walk(r.type);
    });
  }
}

export { generatePythonSdk };
