import { copyFile, mkdir, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type {
  ApiSpec,
  ArrayType,
  AuthScheme,
  EnumType,
  ObjectType,
  Operation,
  Property,
  ServiceGroup,
  TypeRef,
} from "../ir.js";

function toPascalCase(slug: string): string {
  return slug
    .split("-")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

function toCamelCase(slug: string): string {
  const pascal = toPascalCase(slug);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function typeRefToTs(ref: TypeRef): string {
  switch (ref.kind) {
    case "primitive":
      if (ref.type === "integer") return "number";
      return ref.type;
    case "ref":
      return ref.name;
    case "array":
      return `${typeRefToTs(ref.items)}[]`;
    case "enum":
      return ref.values.map((v) => (typeof v === "string" ? `"${v}"` : v)).join(" | ");
    case "union": {
      const mapped = ref.variants.map(typeRefToTs).filter(Boolean);
      return mapped.length > 0 ? mapped.join(" | ") : "unknown";
    }
    case "object":
      if (ref.name) return ref.name;
      return inlineObjectType(ref);
    case "map":
      return `Record<string, ${typeRefToTs(ref.valueType)}>`;
  }
}

function formatJsDoc(description: string, indent = ""): string {
  const safe = description.replace(/\*\//g, "* /");
  if (safe.includes("\n")) {
    const lines = [`${indent}/**`];
    for (const line of safe.split("\n")) {
      lines.push(`${indent} * ${line.trimEnd()}`);
    }
    lines.push(`${indent} */`);
    return lines.join("\n");
  }
  return `${indent}/** ${safe} */`;
}

function safePropertyName(name: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : `"${name}"`;
}

function inlineObjectType(obj: ObjectType): string {
  if (obj.properties.length === 0) return "Record<string, unknown>";
  const fields = obj.properties
    .map((p) => {
      const opt = p.required ? "" : "?";
      return `  ${safePropertyName(p.name)}${opt}: ${typeRefToTs(p.type)}${p.nullable ? " | null" : ""};`;
    })
    .join("\n");
  return `{\n${fields}\n}`;
}

function generateInterface(model: ObjectType): string {
  const lines: string[] = [];
  if (model.description) {
    lines.push(formatJsDoc(model.description));
  }
  lines.push(`export interface ${model.name} {`);

  for (const prop of model.properties) {
    if (prop.description) {
      lines.push(formatJsDoc(prop.description, "  "));
    }
    const opt = prop.required ? "" : "?";
    const nullable = prop.nullable ? " | null" : "";
    lines.push(`  ${safePropertyName(prop.name)}${opt}: ${typeRefToTs(prop.type)}${nullable};`);
  }

  lines.push("}");
  return lines.join("\n");
}

function generateEnumType(model: EnumType): string {
  const values = model.values
    .map((v) => (typeof v === "string" ? `"${v}"` : v))
    .join(" | ");
  const lines: string[] = [];
  if (model.description) {
    lines.push(`/** ${model.description} */`);
  }
  lines.push(`export type ${model.name} = ${values || "string"};`);
  return lines.join("\n");
}

function generateModels(spec: ApiSpec): string {
  const parts: string[] = ["// Generated by Ingot — do not edit manually.\n"];

  for (const [, model] of spec.models) {
    if (model.kind === "object") {
      parts.push(generateInterface(model as ObjectType));
    } else if (model.kind === "enum") {
      parts.push(generateEnumType(model as EnumType));
    } else {
      const resolved = typeRefToTs(model);
      if (!resolved || resolved === model.name || resolved.includes(model.name)) {
        parts.push(`export type ${model.name} = unknown;`);
      } else {
        parts.push(`export type ${model.name} = ${resolved};`);
      }
    }
    parts.push("");
  }

  return parts.join("\n");
}

interface MethodParamShape {
  signature: string;
  bodyAccess: string | null;
}

function buildMethodParams(op: Operation): MethodParamShape {
  const params: string[] = [];

  for (const param of op.parameters.filter((p) => p.location === "path")) {
    params.push(`${param.name}: ${typeRefToTs(param.type)}`);
  }

  const queryParams = op.parameters.filter((p) => p.location === "query");
  const hasBody = !!op.requestBody;
  let bodyAccess: string | null = null;

  if (hasBody && queryParams.length === 0) {
    const bodyType = typeRefToTs(op.requestBody!.type);
    const opt = op.requestBody!.required ? "" : "?";
    params.push(`body${opt}: ${bodyType}`);
    bodyAccess = "body";
  } else if (hasBody || queryParams.length > 0) {
    const optionsFields: string[] = [];

    for (const q of queryParams) {
      const opt = q.required ? "" : "?";
      optionsFields.push(`${q.name}${opt}: ${typeRefToTs(q.type)}`);
    }

    if (hasBody) {
      const bodyType = typeRefToTs(op.requestBody!.type);
      const opt = op.requestBody!.required ? "" : "?";
      optionsFields.push(`body${opt}: ${bodyType}`);
      bodyAccess = "options.body";
    }

    if (optionsFields.length > 0) {
      params.push(`options: { ${optionsFields.join("; ")} }`);
    }
  }

  params.push("requestConfig?: RequestConfig");
  return { signature: params.join(", "), bodyAccess };
}

function buildUrl(op: Operation): string {
  const pathParams = op.parameters.filter((p) => p.location === "path");
  if (pathParams.length === 0) {
    return `"${op.path}"`;
  }
  const wireToCode = new Map(pathParams.map((p) => [p.wireName, p.name]));
  const interpolated = op.path.replace(
    /\{([^}]+)\}/g,
    (_, wireName) => `\${${wireToCode.get(wireName) ?? wireName}}`,
  );
  return `\`${interpolated}\``;
}

function buildQueryString(op: Operation): string | null {
  const queryParams = op.parameters.filter((p) => p.location === "query");
  if (queryParams.length === 0) return null;
  const entries = queryParams.map((p) => `"${p.wireName}": options.${p.name}`);
  return `{ ${entries.join(", ")} }`;
}

function returnType(op: Operation): string {
  const successResponse = op.responses.find(
    (r) => r.statusCode >= 200 && r.statusCode < 300 && r.type,
  );
  if (!successResponse?.type) return "void";
  return typeRefToTs(successResponse.type);
}

function paginatedItemType(op: Operation): string | null {
  if (!op.pagination?.dataField) return null;
  const successResponse = op.responses.find(
    (r) => r.statusCode >= 200 && r.statusCode < 300 && r.type,
  );
  if (!successResponse?.type || successResponse.type.kind !== "object") return null;
  const obj = successResponse.type as ObjectType;
  const field = obj.properties.find((p) => p.name === op.pagination!.dataField);
  if (!field || field.type.kind !== "array") return null;
  return typeRefToTs((field.type as ArrayType).items);
}

function generateMethodName(op: Operation): string {
  return op.id.replace(/[^a-zA-Z0-9]/g, " ").replace(/\s+(.)/g, (_, c) => c.toUpperCase()).replace(/\s/g, "");
}

function buildMethodJsDoc(op: Operation): string | null {
  const hasDescription = !!op.description;
  const paramsWithDesc = op.parameters.filter((p) => p.description);
  if (!hasDescription && paramsWithDesc.length === 0) return null;

  const docLines: string[] = ["  /**"];
  if (op.description) {
    const safe = op.description.replace(/\*\//g, "* /");
    for (const line of safe.split("\n")) {
      docLines.push(`   * ${line.trimEnd()}`);
    }
  }
  if (hasDescription && paramsWithDesc.length > 0) {
    docLines.push("   *");
  }
  for (const p of paramsWithDesc) {
    const desc = p.description!.replace(/\*\//g, "* /").split("\n")[0];
    docLines.push(`   * @param ${p.name} - ${desc}`);
  }
  docLines.push("   */");
  return docLines.join("\n");
}

function generateServiceGroup(group: ServiceGroup): { code: string; needsPagination: boolean } {
  let needsPagination = false;

  const methods = group.operations.map((op) => {
    const name = generateMethodName(op);
    const { signature, bodyAccess } = buildMethodParams(op);
    const url = buildUrl(op);
    const query = buildQueryString(op);
    const method = op.method.toUpperCase();
    const itemType = paginatedItemType(op);

    const lines: string[] = [];
    const docParts = buildMethodJsDoc(op);
    if (docParts) {
      lines.push(docParts);
    }

    if (itemType && op.pagination) {
      needsPagination = true;
      const pageClass = op.pagination.style === "cursor" ? "CursorPage" : "OffsetPage";
      lines.push(`  ${name}(${signature}): ${pageClass}<${itemType}> {`);

      if (op.pagination.style === "cursor") {
        lines.push(`    return new CursorPage(this.client, {`);
        lines.push(`      method: "${method}",`);
        lines.push(`      path: ${url},`);
        if (query) lines.push(`      query: ${query},`);
        lines.push(`      requestConfig,`);
        lines.push(`    }, {`);
        lines.push(`      dataField: "${op.pagination.dataField}",`);
        lines.push(`      cursorField: "${op.pagination.cursorResponsePath ?? "next_cursor"}",`);
        lines.push(`      cursorQueryParam: "${op.pagination.cursorParam ?? "cursor"}",`);
        lines.push(`    });`);
      } else {
        lines.push(`    return new OffsetPage(this.client, {`);
        lines.push(`      method: "${method}",`);
        lines.push(`      path: ${url},`);
        if (query) lines.push(`      query: ${query},`);
        lines.push(`      requestConfig,`);
        lines.push(`    }, {`);
        lines.push(`      dataField: "${op.pagination.dataField}",`);
        lines.push(`      limitParam: "${op.pagination.limitParam}",`);
        lines.push(`      offsetParam: "${op.pagination.offsetParam ?? "offset"}",`);
        lines.push(`    });`);
      }
      lines.push(`  }`);
    } else {
      const ret = returnType(op);
      lines.push(`  async ${name}(${signature}): Promise<${ret}> {`);
      lines.push(`    return this.client.request({`);
      lines.push(`      method: "${method}",`);
      lines.push(`      path: ${url},`);
      if (query) {
        lines.push(`      query: ${query},`);
      }
      if (bodyAccess) {
        lines.push(`      body: ${bodyAccess},`);
      }
      lines.push(`      requestConfig,`);
      lines.push(`    });`);
      lines.push(`  }`);
    }
    return lines.join("\n");
  });

  const className = toPascalCase(group.name);
  const lines = [
    `export class ${className}Resource {`,
    `  constructor(private client: IngotClient) {}`,
    "",
    ...methods.map((m) => m),
    "}",
  ];

  return { code: lines.join("\n"), needsPagination };
}

function generateClientClass(spec: ApiSpec): string {
  const groups = spec.groups.map((g) => {
    const className = toPascalCase(g.name);
    return { fieldName: toCamelCase(g.name), className: `${className}Resource` };
  });

  const lines: string[] = [
    `export interface ClientConfig {`,
    `  baseUrl?: string;`,
  ];

  const emittedFields = new Set<string>();
  for (const auth of spec.auth) {
    if ((auth.strategy === "bearer" || auth.strategy === "apiKey") && !emittedFields.has("apiKey")) {
      lines.push(`  apiKey?: string;`);
      emittedFields.add("apiKey");
    } else if (auth.strategy === "basic" && !emittedFields.has("basic")) {
      lines.push(`  username?: string;`);
      lines.push(`  password?: string;`);
      emittedFields.add("basic");
    }
  }

  lines.push(
    `  timeout?: number;`,
    `  maxRetries?: number;`,
    `}`,
    "",
    `export class IngotClient extends BaseClient {`,
  );

  for (const g of groups) {
    lines.push(`  readonly ${g.fieldName}: ${g.className};`);
  }

  const authHeaders: string[] = [];
  for (const auth of spec.auth) {
    if (auth.strategy === "bearer") {
      authHeaders.push(
        `    if (config.apiKey) headers["Authorization"] = \`Bearer \${config.apiKey}\`;`,
      );
    } else if (auth.strategy === "apiKey") {
      const header = auth.headerName ?? "X-API-Key";
      authHeaders.push(
        `    if (config.apiKey) headers["${header}"] = config.apiKey;`,
      );
    }
  }

  lines.push(
    "",
    `  constructor(config: ClientConfig = {}) {`,
    `    const headers: Record<string, string> = {};`,
  );
  lines.push(...authHeaders);
  lines.push(
    `    super({`,
    `      baseUrl: config.baseUrl ?? "${spec.baseUrl}",`,
    `      timeout: config.timeout,`,
    `      maxRetries: config.maxRetries,`,
    `      headers,`,
    `    });`,
  );

  for (const g of groups) {
    lines.push(`    this.${g.fieldName} = new ${g.className}(this);`);
  }

  lines.push(
    `  }`,
    "}",
  );

  return lines.join("\n");
}

function generatePackageJson(spec: ApiSpec): string {
  const name = spec.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return JSON.stringify(
    {
      name,
      version: spec.version,
      description: spec.description ?? `TypeScript SDK for ${spec.name}`,
      type: "module",
      main: "./dist/index.js",
      types: "./dist/index.d.ts",
      exports: {
        ".": {
          types: "./dist/index.d.ts",
          import: "./dist/index.js",
        },
      },
      files: ["dist", "README.md"],
      scripts: {
        build: "tsc",
        prepublishOnly: "npm run build",
      },
      engines: {
        node: ">=18",
      },
      dependencies: {},
      devDependencies: {
        typescript: "^5.8.0",
      },
    },
    null,
    2,
  );
}

function generateReadme(spec: ApiSpec): string {
  const pkgName = spec.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const lines: string[] = [];

  lines.push(`# ${spec.name} TypeScript SDK`);
  lines.push("");
  if (spec.description) {
    lines.push(spec.description);
    lines.push("");
  }
  lines.push("## Installation");
  lines.push("");
  lines.push("```sh");
  lines.push(`npm install ${pkgName}`);
  lines.push("```");
  lines.push("");

  lines.push("## Usage");
  lines.push("");

  const hasApiKey = spec.auth.some((a) => a.strategy === "bearer" || a.strategy === "apiKey");
  const hasBasic = spec.auth.some((a) => a.strategy === "basic");

  lines.push("```typescript");
  lines.push(`import { IngotClient } from "${pkgName}";`);
  lines.push("");

  if (hasApiKey) {
    lines.push(`const client = new IngotClient({`);
    lines.push(`  apiKey: process.env.API_KEY,`);
    lines.push(`});`);
  } else if (hasBasic) {
    lines.push(`const client = new IngotClient({`);
    lines.push(`  username: process.env.USERNAME,`);
    lines.push(`  password: process.env.PASSWORD,`);
    lines.push(`});`);
  } else {
    lines.push(`const client = new IngotClient();`);
  }
  lines.push("");

  const exampleGroup = spec.groups[0];
  if (exampleGroup) {
    const fieldName = toCamelCase(exampleGroup.name);
    const getOp = exampleGroup.operations.find((op) => op.method === "get" && op.parameters.filter((p) => p.location === "path").length === 0);
    const listOp = exampleGroup.operations.find((op) => op.method === "get" && op.parameters.some((p) => p.location === "query"));
    const target = listOp ?? getOp;

    if (target) {
      const methodName = generateMethodName(target);
      const hasPagination = !!paginatedItemType(target);
      if (hasPagination) {
        lines.push(`for await (const item of client.${fieldName}.${methodName}({})) {`);
        lines.push(`  console.log(item);`);
        lines.push(`}`);
      } else {
        lines.push(`const result = await client.${fieldName}.${methodName}();`);
        lines.push(`console.log(result);`);
      }
    }
  }
  lines.push("```");
  lines.push("");

  lines.push("## Configuration");
  lines.push("");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  if (hasApiKey) {
    lines.push("| `apiKey` | `string` | — | API key for authentication |");
  }
  if (hasBasic) {
    lines.push("| `username` | `string` | — | Username for basic auth |");
    lines.push("| `password` | `string` | — | Password for basic auth |");
  }
  lines.push(`| \`baseUrl\` | \`string\` | \`${spec.baseUrl}\` | API base URL |`);
  lines.push("| `timeout` | `number` | `30000` | Request timeout in ms |");
  lines.push("| `maxRetries` | `number` | `2` | Max retry attempts |");
  lines.push("");

  lines.push("## Per-Request Options");
  lines.push("");
  lines.push("Every method accepts an optional `RequestConfig` as the last argument:");
  lines.push("");
  lines.push("```typescript");
  if (exampleGroup) {
    const fieldName = toCamelCase(exampleGroup.name);
    const postOp = exampleGroup.operations.find((op) => op.method === "post");
    if (postOp) {
      const methodName = generateMethodName(postOp);
      lines.push(`await client.${fieldName}.${methodName}(body, {`);
    } else {
      lines.push(`await client.someResource.someMethod(params, {`);
    }
  } else {
    lines.push(`await client.someResource.someMethod(params, {`);
  }
  lines.push(`  timeout: 5000,`);
  lines.push(`  maxRetries: 0,`);
  lines.push(`  headers: { "X-Custom": "value" },`);
  lines.push(`});`);
  lines.push("```");
  lines.push("");

  lines.push("## Resources");
  lines.push("");
  for (const group of spec.groups) {
    const fieldName = toCamelCase(group.name);
    lines.push(`- \`client.${fieldName}\``);
    for (const op of group.operations) {
      const methodName = generateMethodName(op);
      const desc = op.description ? ` — ${op.description.split("\n")[0]}` : "";
      lines.push(`  - \`.${methodName}()\`${desc}`);
    }
  }
  lines.push("");

  lines.push("## Error Handling");
  lines.push("");
  lines.push("```typescript");
  lines.push(`import { APIError, RateLimitError, TimeoutError } from "${pkgName}";`);
  lines.push("");
  lines.push("try {");
  lines.push(`  await client.${toCamelCase(spec.groups[0]?.name ?? "resource")}.someMethod();`);
  lines.push("} catch (err) {");
  lines.push("  if (err instanceof RateLimitError) {");
  lines.push(`    console.log("Rate limited, retry after:", err.headers.get("retry-after"));`);
  lines.push("  } else if (err instanceof TimeoutError) {");
  lines.push("    console.log(\"Request timed out\");");
  lines.push("  } else if (err instanceof APIError) {");
  lines.push("    console.log(err.status, err.body);");
  lines.push("  }");
  lines.push("}");
  lines.push("```");
  lines.push("");

  lines.push("---");
  lines.push("");
  lines.push("Generated by [Ingot](https://github.com/loperdev/ingot).");
  lines.push("");

  return lines.join("\n");
}

function generateTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "Node16",
        moduleResolution: "Node16",
        outDir: "dist",
        rootDir: "src",
        strict: true,
        declaration: true,
        esModuleInterop: true,
        skipLibCheck: true,
      },
      include: ["src"],
    },
    null,
    2,
  );
}

function generateEntrypoint(spec: ApiSpec): string {
  const lines = [
    "// Generated by Ingot — do not edit manually.\n",
    `export { IngotClient, type ClientConfig } from "./client.js";`,
    `export {`,
    `  APIError,`,
    `  AuthenticationError,`,
    `  PermissionDeniedError,`,
    `  NotFoundError,`,
    `  RateLimitError,`,
    `  InternalServerError,`,
    `  TimeoutError,`,
    `} from "./_runtime/error.js";`,
    `export type { RequestConfig } from "./_runtime/client.js";`,
    `export { Stream } from "./_runtime/streaming.js";`,
    `export { CursorPage, OffsetPage } from "./_runtime/pagination.js";`,
  ];

  const modelNames: string[] = [];
  for (const [name] of spec.models) {
    modelNames.push(name);
  }
  if (modelNames.length > 0) {
    lines.push(`export type { ${modelNames.join(", ")} } from "./models.js";`);
  }

  for (const group of spec.groups) {
    const className = toPascalCase(group.name);
    lines.push(`export { ${className}Resource } from "./resources/${group.name}.js";`);
  }

  return lines.join("\n");
}

const RUNTIME_DIR = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "runtime",
  "typescript",
);

async function copyRuntime(srcDir: string): Promise<void> {
  const runtimeDir = join(srcDir, "_runtime");
  await mkdir(runtimeDir, { recursive: true });
  for (const file of ["client.ts", "error.ts", "pagination.ts", "streaming.ts"]) {
    await copyFile(join(RUNTIME_DIR, file), join(runtimeDir, file));
  }
}

async function generateTypescriptSdk(
  spec: ApiSpec,
  outputDir: string,
): Promise<void> {
  const srcDir = join(outputDir, "src");
  const resourcesDir = join(srcDir, "resources");
  await mkdir(resourcesDir, { recursive: true });

  await copyRuntime(srcDir);
  await writeFile(join(outputDir, "package.json"), generatePackageJson(spec));
  await writeFile(join(outputDir, "tsconfig.json"), generateTsConfig());
  await writeFile(join(outputDir, "README.md"), generateReadme(spec));
  await writeFile(join(srcDir, "models.ts"), generateModels(spec));

  const clientParts: string[] = [
    "// Generated by Ingot — do not edit manually.\n",
    `import { BaseClient } from "./_runtime/client.js";`,
  ];
  for (const group of spec.groups) {
    const className = toPascalCase(group.name);
    clientParts.push(
      `import { ${className}Resource } from "./resources/${group.name}.js";`,
    );
  }
  clientParts.push("");
  clientParts.push(generateClientClass(spec));

  await writeFile(join(srcDir, "client.ts"), clientParts.join("\n"));

  for (const group of spec.groups) {
    const imports: Set<string> = new Set();
    collectModelRefs(group, spec, imports);

    const parts: string[] = ["// Generated by Ingot — do not edit manually.\n"];
    if (imports.size > 0) {
      parts.push(
        `import type { ${[...imports].join(", ")} } from "../models.js";`,
      );
    }
    parts.push(`import type { IngotClient } from "../client.js";`);
    parts.push(`import type { RequestConfig } from "../_runtime/client.js";`);
    const { code, needsPagination } = generateServiceGroup(group);
    if (needsPagination) {
      parts.push(`import { CursorPage, OffsetPage } from "../_runtime/pagination.js";`);
    }
    parts.push("");
    parts.push(code);
    parts.push("");

    await writeFile(join(resourcesDir, `${group.name}.ts`), parts.join("\n"));
  }

  await writeFile(join(srcDir, "index.ts"), generateEntrypoint(spec));
}

function collectModelRefs(
  group: ServiceGroup,
  spec: ApiSpec,
  refs: Set<string>,
): void {
  function walk(t: TypeRef): void {
    switch (t.kind) {
      case "ref":
        if (spec.models.has(t.name)) refs.add(t.name);
        break;
      case "array":
        walk(t.items);
        break;
      case "union":
        t.variants.forEach(walk);
        break;
      case "object":
        t.properties.forEach((p) => walk(p.type));
        break;
      case "map":
        walk(t.valueType);
        break;
    }
  }

  for (const op of group.operations) {
    op.parameters.forEach((p) => walk(p.type));
    if (op.requestBody) walk(op.requestBody.type);
    op.responses.forEach((r) => {
      if (r.type) walk(r.type);
    });
  }
}

export { generateTypescriptSdk };
