import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type {
  ApiSpec,
  AuthScheme,
  EnumType,
  ObjectType,
  Operation,
  Property,
  ServiceGroup,
  TypeRef,
} from "../ir.js";

function typeRefToTs(ref: TypeRef): string {
  switch (ref.kind) {
    case "primitive":
      if (ref.type === "integer") return "number";
      return ref.type;
    case "ref":
      return ref.name;
    case "array":
      return `${typeRefToTs(ref.items)}[]`;
    case "enum":
      return ref.values.map((v) => (typeof v === "string" ? `"${v}"` : v)).join(" | ");
    case "union":
      return ref.variants.map(typeRefToTs).join(" | ");
    case "object":
      if (ref.name) return ref.name;
      return inlineObjectType(ref);
    case "map":
      return `Record<string, ${typeRefToTs(ref.valueType)}>`;
  }
}

function inlineObjectType(obj: ObjectType): string {
  if (obj.properties.length === 0) return "Record<string, unknown>";
  const fields = obj.properties
    .map((p) => {
      const opt = p.required ? "" : "?";
      return `  ${p.name}${opt}: ${typeRefToTs(p.type)}${p.nullable ? " | null" : ""};`;
    })
    .join("\n");
  return `{\n${fields}\n}`;
}

function generateInterface(model: ObjectType): string {
  const lines: string[] = [];
  if (model.description) {
    lines.push(`/** ${model.description} */`);
  }
  lines.push(`export interface ${model.name} {`);

  for (const prop of model.properties) {
    if (prop.description) {
      lines.push(`  /** ${prop.description} */`);
    }
    const opt = prop.required ? "" : "?";
    const nullable = prop.nullable ? " | null" : "";
    lines.push(`  ${prop.name}${opt}: ${typeRefToTs(prop.type)}${nullable};`);
  }

  lines.push("}");
  return lines.join("\n");
}

function generateEnumType(model: EnumType): string {
  const values = model.values
    .map((v) => (typeof v === "string" ? `"${v}"` : v))
    .join(" | ");
  const lines: string[] = [];
  if (model.description) {
    lines.push(`/** ${model.description} */`);
  }
  lines.push(`export type ${model.name} = ${values};`);
  return lines.join("\n");
}

function generateModels(spec: ApiSpec): string {
  const parts: string[] = ["// Generated by Ingot — do not edit manually.\n"];

  for (const [, model] of spec.models) {
    if (model.kind === "object") {
      parts.push(generateInterface(model));
    } else if (model.kind === "enum") {
      parts.push(generateEnumType(model));
    }
    parts.push("");
  }

  return parts.join("\n");
}

function buildMethodParams(op: Operation): string {
  const params: string[] = [];

  for (const param of op.parameters.filter((p) => p.location === "path")) {
    params.push(`${param.name}: ${typeRefToTs(param.type)}`);
  }

  const queryParams = op.parameters.filter((p) => p.location === "query");
  const hasBody = !!op.requestBody;

  if (hasBody || queryParams.length > 0) {
    const optionsFields: string[] = [];

    for (const q of queryParams) {
      const opt = q.required ? "" : "?";
      optionsFields.push(`${q.name}${opt}: ${typeRefToTs(q.type)}`);
    }

    if (hasBody) {
      const bodyType = typeRefToTs(op.requestBody!.type);
      const opt = op.requestBody!.required ? "" : "?";
      optionsFields.push(`body${opt}: ${bodyType}`);
    }

    if (optionsFields.length > 0) {
      params.push(`options: { ${optionsFields.join("; ")} }`);
    }
  }

  return params.join(", ");
}

function buildUrl(op: Operation): string {
  if (!op.parameters.some((p) => p.location === "path")) {
    return `"${op.path}"`;
  }
  const interpolated = op.path.replace(
    /\{(\w+)\}/g,
    (_, name) => `\${${name}}`,
  );
  return `\`${interpolated}\``;
}

function buildQueryString(op: Operation): string | null {
  const queryParams = op.parameters.filter((p) => p.location === "query");
  if (queryParams.length === 0) return null;
  const entries = queryParams.map((p) => `${p.name}: options.${p.name}`);
  return `{ ${entries.join(", ")} }`;
}

function returnType(op: Operation): string {
  const successResponse = op.responses.find(
    (r) => r.statusCode >= 200 && r.statusCode < 300 && r.type,
  );
  if (!successResponse?.type) return "void";
  return typeRefToTs(successResponse.type);
}

function generateMethodName(op: Operation): string {
  return op.id.replace(/[-_.]/g, " ").replace(/\s+(.)/g, (_, c) => c.toUpperCase()).replace(/\s/g, "");
}

function generateServiceGroup(group: ServiceGroup): string {
  const methods = group.operations.map((op) => {
    const name = generateMethodName(op);
    const params = buildMethodParams(op);
    const ret = returnType(op);
    const url = buildUrl(op);
    const query = buildQueryString(op);
    const method = op.method.toUpperCase();

    const lines: string[] = [];
    if (op.description) {
      lines.push(`  /** ${op.description} */`);
    }
    lines.push(`  async ${name}(${params}): Promise<${ret}> {`);
    lines.push(`    return this.client.request({`);
    lines.push(`      method: "${method}",`);
    lines.push(`      path: ${url},`);
    if (query) {
      lines.push(`      query: ${query},`);
    }
    if (op.requestBody) {
      lines.push(`      body: options.body,`);
    }
    lines.push(`    });`);
    lines.push(`  }`);
    return lines.join("\n");
  });

  const className = group.name.charAt(0).toUpperCase() + group.name.slice(1);
  const lines = [
    `export class ${className}Resource {`,
    `  constructor(private client: IngotClient) {}`,
    "",
    ...methods.map((m) => m),
    "}",
  ];

  return lines.join("\n");
}

function generateClientClass(spec: ApiSpec): string {
  const groups = spec.groups.map((g) => {
    const className = g.name.charAt(0).toUpperCase() + g.name.slice(1);
    return { fieldName: g.name, className: `${className}Resource` };
  });

  const lines: string[] = [
    "// Generated by Ingot — do not edit manually.\n",
    `export interface ClientConfig {`,
    `  baseUrl?: string;`,
  ];

  for (const auth of spec.auth) {
    if (auth.strategy === "bearer") {
      lines.push(`  apiKey?: string;`);
    } else if (auth.strategy === "apiKey") {
      lines.push(`  apiKey?: string;`);
    } else if (auth.strategy === "basic") {
      lines.push(`  username?: string;`);
      lines.push(`  password?: string;`);
    }
  }

  lines.push(
    `  timeout?: number;`,
    `  maxRetries?: number;`,
    `}`,
    "",
    generateRequestType(),
    "",
    `export class IngotClient {`,
    `  private baseUrl: string;`,
    `  private headers: Record<string, string>;`,
    `  private timeout: number;`,
    `  private maxRetries: number;`,
    "",
  );

  for (const g of groups) {
    lines.push(`  readonly ${g.fieldName}: ${g.className};`);
  }

  lines.push(
    "",
    `  constructor(config: ClientConfig = {}) {`,
    `    this.baseUrl = config.baseUrl ?? "${spec.baseUrl}";`,
    `    this.timeout = config.timeout ?? 30_000;`,
    `    this.maxRetries = config.maxRetries ?? 2;`,
    `    this.headers = { "Content-Type": "application/json" };`,
  );

  for (const auth of spec.auth) {
    if (auth.strategy === "bearer") {
      lines.push(
        `    if (config.apiKey) this.headers["Authorization"] = \`Bearer \${config.apiKey}\`;`,
      );
    } else if (auth.strategy === "apiKey") {
      const header = auth.headerName ?? "X-API-Key";
      lines.push(
        `    if (config.apiKey) this.headers["${header}"] = config.apiKey;`,
      );
    }
  }

  for (const g of groups) {
    lines.push(`    this.${g.fieldName} = new ${g.className}(this);`);
  }

  lines.push(
    `  }`,
    "",
    generateRequestMethod(),
    "}",
  );

  return lines.join("\n");
}

function generateRequestType(): string {
  return [
    `interface RequestOptions {`,
    `  method: string;`,
    `  path: string;`,
    `  query?: Record<string, unknown>;`,
    `  body?: unknown;`,
    `}`,
  ].join("\n");
}

function generateRequestMethod(): string {
  return [
    `  async request<T>(options: RequestOptions): Promise<T> {`,
    `    const url = new URL(options.path, this.baseUrl);`,
    `    if (options.query) {`,
    `      for (const [key, value] of Object.entries(options.query)) {`,
    `        if (value !== undefined && value !== null) {`,
    `          url.searchParams.set(key, String(value));`,
    `        }`,
    `      }`,
    `    }`,
    ``,
    `    let lastError: Error | null = null;`,
    `    for (let attempt = 0; attempt <= this.maxRetries; attempt++) {`,
    `      if (attempt > 0) {`,
    `        await new Promise((r) => setTimeout(r, Math.min(1000 * 2 ** attempt, 8000)));`,
    `      }`,
    ``,
    `      try {`,
    `        const controller = new AbortController();`,
    `        const timeoutId = setTimeout(() => controller.abort(), this.timeout);`,
    ``,
    `        const response = await fetch(url.toString(), {`,
    `          method: options.method,`,
    `          headers: this.headers,`,
    `          body: options.body ? JSON.stringify(options.body) : undefined,`,
    `          signal: controller.signal,`,
    `        });`,
    ``,
    `        clearTimeout(timeoutId);`,
    ``,
    `        if (!response.ok) {`,
    `          const text = await response.text().catch(() => "");`,
    `          const error = new Error(\`\${options.method} \${options.path} failed: \${response.status} \${text}\`);`,
    `          if (response.status >= 500 || response.status === 429) {`,
    `            lastError = error;`,
    `            continue;`,
    `          }`,
    `          throw error;`,
    `        }`,
    ``,
    `        if (response.status === 204) return undefined as T;`,
    `        return (await response.json()) as T;`,
    `      } catch (err) {`,
    `        if (err instanceof Error && err.name === "AbortError") {`,
    `          lastError = new Error(\`Request timed out: \${options.method} \${options.path}\`);`,
    `          continue;`,
    `        }`,
    `        throw err;`,
    `      }`,
    `    }`,
    ``,
    `    throw lastError ?? new Error("Request failed after retries");`,
    `  }`,
  ].join("\n");
}

function generatePackageJson(spec: ApiSpec): string {
  const name = spec.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return JSON.stringify(
    {
      name,
      version: spec.version,
      description: spec.description ?? `TypeScript SDK for ${spec.name}`,
      type: "module",
      main: "./dist/index.js",
      types: "./dist/index.d.ts",
      scripts: {
        build: "tsc",
      },
      dependencies: {},
      devDependencies: {
        typescript: "^5.8.0",
      },
    },
    null,
    2,
  );
}

function generateTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "Node16",
        moduleResolution: "Node16",
        outDir: "dist",
        rootDir: "src",
        strict: true,
        declaration: true,
        esModuleInterop: true,
        skipLibCheck: true,
      },
      include: ["src"],
    },
    null,
    2,
  );
}

function generateEntrypoint(spec: ApiSpec): string {
  const lines = [
    "// Generated by Ingot — do not edit manually.\n",
    `export { IngotClient, type ClientConfig } from "./client.js";`,
  ];

  const modelNames: string[] = [];
  for (const [name] of spec.models) {
    modelNames.push(name);
  }
  if (modelNames.length > 0) {
    lines.push(`export type { ${modelNames.join(", ")} } from "./models.js";`);
  }

  for (const group of spec.groups) {
    const className = group.name.charAt(0).toUpperCase() + group.name.slice(1);
    lines.push(`export { ${className}Resource } from "./resources/${group.name}.js";`);
  }

  return lines.join("\n");
}

async function generateTypescriptSdk(
  spec: ApiSpec,
  outputDir: string,
): Promise<void> {
  const srcDir = join(outputDir, "src");
  const resourcesDir = join(srcDir, "resources");
  await mkdir(resourcesDir, { recursive: true });

  await writeFile(join(outputDir, "package.json"), generatePackageJson(spec));
  await writeFile(join(outputDir, "tsconfig.json"), generateTsConfig());
  await writeFile(join(srcDir, "models.ts"), generateModels(spec));

  // Build client with all resource imports
  const clientParts: string[] = [
    "// Generated by Ingot — do not edit manually.\n",
  ];
  for (const group of spec.groups) {
    const className = group.name.charAt(0).toUpperCase() + group.name.slice(1);
    clientParts.push(
      `import { ${className}Resource } from "./resources/${group.name}.js";`,
    );
  }
  clientParts.push("");
  clientParts.push(generateClientClass(spec));

  await writeFile(join(srcDir, "client.ts"), clientParts.join("\n"));

  for (const group of spec.groups) {
    const imports: Set<string> = new Set();
    collectModelRefs(group, spec, imports);

    const parts: string[] = ["// Generated by Ingot — do not edit manually.\n"];
    if (imports.size > 0) {
      parts.push(
        `import type { ${[...imports].join(", ")} } from "../models.js";`,
      );
    }
    parts.push(`import type { IngotClient } from "../client.js";\n`);
    parts.push(generateServiceGroup(group));
    parts.push("");

    await writeFile(join(resourcesDir, `${group.name}.ts`), parts.join("\n"));
  }

  await writeFile(join(srcDir, "index.ts"), generateEntrypoint(spec));
}

function collectModelRefs(
  group: ServiceGroup,
  spec: ApiSpec,
  refs: Set<string>,
): void {
  function walk(t: TypeRef): void {
    switch (t.kind) {
      case "ref":
        if (spec.models.has(t.name)) refs.add(t.name);
        break;
      case "array":
        walk(t.items);
        break;
      case "union":
        t.variants.forEach(walk);
        break;
      case "object":
        t.properties.forEach((p) => walk(p.type));
        break;
      case "map":
        walk(t.valueType);
        break;
    }
  }

  for (const op of group.operations) {
    op.parameters.forEach((p) => walk(p.type));
    if (op.requestBody) walk(op.requestBody.type);
    op.responses.forEach((r) => {
      if (r.type) walk(r.type);
    });
  }
}

export { generateTypescriptSdk };
